name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install zip-release-files

      - name: Create release files
        run: |
          mkdir -p release
          cp -r custom_components release/
          cp *.md release/
          cp *.yaml release/
          cp LICENSE release/
          cp VERSION release/

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
